name: flutter_screen_recording
description: A new Flutter plugin for record the screen. This plugin can be used for record the screen on android, iOS devices.
homepage: "https://github.com/HollySite/flutter_screen_recording"

publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_foreground_task: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.isvisoft.flutter_screen_recording
        pluginClass: FlutterScreenRecordingPlugin
      ios:
        pluginClass: FlutterScreenRecordingPlugin
